name: JavaScript CI

on:
  push:
    branches:
      - main
      - develop
      - feature/*
    paths:
      - "javascript/**"
      - .github/workflows/javascript_ci.yml
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "javascript/**"
      - .github/workflows/javascript_ci.yml

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*", "18", "20"]

    defaults:
      run:
        working-directory: ./javascript

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build TypeScript
        run: npm run build

      - name: List dist files
        run: ls dist/

      - name: Check my secret
        run: echo "$my_secret"
        env:
          my_secret: ${{ secrets.VM_PASSWORD }}

      - name: Check my variable
        run: echo "$my_var"
        env:
          my_var: ${{ vars.VM_NAME }}
