name: Python CI-test

on:     #what will trigger the CI 
    push:
        branches: [main, develop,feature/*]
    pull_request:
        branches: [main,develop]

jobs:
    build_test:
        runs-on: ubuntu-latest

        steps: 
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"
            
            - name: install dependencies
              run: cd python && pip install -r requirements.txt

            - name: Run tests
              run: cd python && PYTHONPATH=. pytest/tests/
