name: Python CI

on:
    push:
        branches: [main, develop, feature/*]
    pull_request:
        branches: [main, develop]

jobs:
    build_test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./python

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run tests
              run: PYTHONPATH=. pytest tests/