name: Python CI

on:
    push:
        branches: [main, develop, feature/*]
        paths:
          - "python/**"
          -  .github/workflows/python_ci.yml
    pull_request:
        branches: [main, develop]
        paths:
          - "python/**"
          -  .github/workflows/python_ci.yml

jobs:
    build_test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./python

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"

            - name: Install Python dependencies
              run: pip install black flake8
              
            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                black: true
                flake8: true

            -  name: Run tests
               run: PYTHONPATH=. pytest tests/